#!/bin/bash
# 快速部署参考卡 - Quick Deployment Reference

echo "=========================================="
echo "LZB微服务 - 快速部署参考"
echo "=========================================="
echo ""
echo "📋 部署前检查清单:"
echo "  □ JDK 17 已安装"
echo "  □ Maven 3.8+ 已安装"
echo "  □ Docker 已安装并运行"
echo "  □ Docker Compose 已安装"
echo "  □ 端口 7573, 8848, 3306, 6379, 389 未被占用"
echo ""
echo "=========================================="
echo "🚀 快速部署命令"
echo "=========================================="
echo ""
echo "1️⃣  导入Nacos配置（必须先执行）:"
echo "   bash scripts/import-nacos-config.sh"
echo ""
echo "2️⃣  设置GitHub OAuth（可选）:"
echo "   export GITHUB_CLIENT_ID=your-client-id"
echo "   export GITHUB_CLIENT_SECRET=your-client-secret"
echo ""
echo "3️⃣  构建和部署所有服务:"
echo "   bash scripts/build-and-deploy.sh"
echo ""
echo "4️⃣  验证部署状态:"
echo "   bash scripts/verify-deployment.sh"
echo ""
echo "=========================================="
echo "🔍 常用检查命令"
echo "=========================================="
echo ""
echo "查看服务状态:"
echo "  docker-compose ps"
echo ""
echo "查看服务日志:"
echo "  docker-compose logs -f lzb-gateway"
echo "  docker-compose logs -f lzb-uaa"
echo "  docker-compose logs -f lzb-product"
echo ""
echo "检查服务健康:"
echo "  curl http://localhost:7573/actuator/health"
echo ""
echo "检查Nacos注册:"
echo "  curl http://localhost:8848/nacos/v1/ns/service/list?pageNo=1&pageSize=10"
echo ""
echo "=========================================="
echo "🌐 访问地址"
echo "=========================================="
echo ""
echo "API Gateway:    http://localhost:7573"
echo "登录页面:       http://localhost:7573/uaa/login"
echo "Nacos控制台:    http://localhost:8848/nacos"
echo "                (用户名/密码: nacos/nacos)"
echo ""
echo "=========================================="
echo "🧪 测试API"
echo "=========================================="
echo ""
echo "1. 获取Token:"
echo "   curl -X POST http://localhost:7573/uaa/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"admin\",\"password\":\"admin123\"}'"
echo ""
echo "2. 查询产品:"
echo "   curl -X GET http://localhost:7573/api/products \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "3. 创建产品:"
echo "   curl -X POST http://localhost:7573/api/products \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\":\"Test\",\"price\":99.99,\"stock\":100}'"
echo ""
echo "=========================================="
echo "🔧 故障排查"
echo "=========================================="
echo ""
echo "服务unhealthy:"
echo "  1. 检查Nacos配置是否已导入"
echo "  2. 运行: bash scripts/import-nacos-config.sh"
echo "  3. 重启: docker-compose restart lzb-gateway lzb-uaa lzb-product"
echo ""
echo "Nacos配置未生效:"
echo "  1. 访问 http://localhost:8848/nacos"
echo "  2. 检查配置列表中是否有以下配置:"
echo "     - common-config.yml"
echo "     - lzb-gateway-docker.yml"
echo "     - lzb-uaa-docker.yml"
echo "     - lzb-product-docker.yml"
echo ""
echo "GitHub OAuth不工作:"
echo "  1. 在Nacos中编辑 lzb-uaa-docker.yml"
echo "  2. 设置正确的 GITHUB_CLIENT_ID 和 GITHUB_CLIENT_SECRET"
echo "  3. 重启: docker-compose restart lzb-uaa"
echo ""
echo "=========================================="
echo "📚 详细文档"
echo "=========================================="
echo ""
echo "完整部署指南:   NACOS_DEPLOYMENT_GUIDE.md"
echo "API测试文档:    API_TESTING.md"
echo "任务完成总结:   TASK_COMPLETION_SUMMARY.md"
echo "项目说明:       README.md"
echo ""
echo "=========================================="
